name: Demo (Acme::Mitey::Cards)
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest' ]
        perl: [ '5.36', '5.34', '5.20' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm -n --installdeps .
      - run: cpanm -n setenv
      - run: cpanm -n Class::XSAccessor
      - run: cpanm -n Perl::Tidy
      - run: prove -lr t
      - name: Compile Acme-Mitey-Cards
        run: perl -I../../lib ../../bin/mite compile
        working-directory: devel.examples/Acme-Mitey-Cards
      - name: Run Acme-Mitey-Cards test suite
        run: prove -lr t
        working-directory: devel.examples/Acme-Mitey-Cards
      - name: Run Acme-Mitey-Cards test suite in PP mode
        run: prove -Msetenv=MITE_PURE_PERL,1 -lr t
        working-directory: devel.examples/Acme-Mitey-Cards
